In [10]:
import torch
import torch.nn as nn 
c=torch.arange(0,10,dtype=torch.float).unsqueeze(1)
print(c.shape)
print(c)

torch.Size([10, 1])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [15]:
d_model=12
import math
x=torch.exp(torch.arange(0,d_model,2).float())*(-math.log(10000.0)/d_model)
print(x.shape)
print(x)

torch.Size([6])
tensor([-7.6753e-01, -5.6713e+00, -4.1906e+01, -3.0964e+02, -2.2880e+03,
        -1.6906e+04])


In [17]:
y=c/x
print(y.shape)

torch.Size([10, 6])


In [38]:
        
seq_len=6
d_model=12

pe=torch.zeros(seq_len,d_model)
        #create a vector for position in seq_len*1

position=torch.arange(0,seq_len,dtype=torch.float).unsqueeze(1)
div_term=torch.exp(torch.arange(0,d_model,2).float())*(-math.log(10000.0)/d_model)         #2 is the step like 2,4,6,8
        #apply sin to even position

pe[:,0::2]=torch.sin(position/div_term)
pe[:,1::2]=torch.cos(position/div_term)
pe.shape

torch.Size([6, 12])

In [41]:
amd=pe.unsqueeze(0)


In [42]:
amd.shape

torch.Size([1, 6, 12])

In [45]:
amd

tensor([[[-0.0000e+00,  1.0000e+00, -0.0000e+00,  1.0000e+00, -0.0000e+00,
           1.0000e+00, -0.0000e+00,  1.0000e+00, -0.0000e+00,  1.0000e+00,
          -0.0000e+00,  1.0000e+00],
         [-9.6433e-01,  2.6472e-01, -1.7541e-01,  9.8449e-01, -2.3861e-02,
           9.9972e-01, -3.2295e-03,  9.9999e-01, -4.3707e-04,  1.0000e+00,
          -5.9151e-05,  1.0000e+00],
         [-5.1055e-01, -8.5985e-01, -3.4539e-01,  9.3846e-01, -4.7708e-02,
           9.9886e-01, -6.4590e-03,  9.9998e-01, -8.7414e-04,  1.0000e+00,
          -1.1830e-04,  1.0000e+00],
         [ 6.9402e-01, -7.1996e-01, -5.0465e-01,  8.6332e-01, -7.1528e-02,
           9.9744e-01, -9.6884e-03,  9.9995e-01, -1.3112e-03,  1.0000e+00,
          -1.7745e-04,  1.0000e+00],
         [ 8.7799e-01,  4.7868e-01, -6.4827e-01,  7.6141e-01, -9.5308e-02,
           9.9545e-01, -1.2918e-02,  9.9992e-01, -1.7483e-03,  1.0000e+00,
          -2.3660e-04,  1.0000e+00],
         [-2.2918e-01,  9.7338e-01, -7.7178e-01,  6.3589e-01, -1.

In [55]:
amd.mean(dim=-1,keepdim=True).shape

torch.Size([1, 6, 1])

In [57]:
a=nn.Linear(12,12)
print(a(pe))

torch.Size([6, 12])


In [60]:
amd.shape

torch.Size([1, 6, 12])

In [76]:
b=amd.view(amd.shape[0],amd.shape[1],3,4).transpose(1,2)
d=(b@b.transpose(-2,-1))
f=d@d
f.shape

torch.Size([1, 3, 6, 6])

In [73]:
import torch
import torch.nn as nn

# Assuming e is the tensor after softmax
e = d.softmax(dim=-1)

# Create a Dropout layer with 90% probability of dropping out neurons
dropout = nn.Dropout(p=0.4)

# Apply dropout to e
e = dropout(e)
e

tensor([[[[0.0000, 0.2695, 0.0836, 0.0892, 0.0000, 0.0000],
          [0.2898, 0.0000, 0.0000, 0.0000, 0.0959, 0.2872],
          [0.1020, 0.0000, 0.6965, 0.0000, 0.0000, 0.1088],
          [0.0000, 0.1020, 0.0000, 0.6965, 0.3287, 0.0000],
          [0.2872, 0.0000, 0.0000, 0.2898, 0.0000, 0.2898],
          [0.0000, 0.0000, 0.0892, 0.0836, 0.2695, 0.0000]],

         [[0.2785, 0.2784, 0.2782, 0.2778, 0.2772, 0.2765],
          [0.2781, 0.2782, 0.0000, 0.2779, 0.2775, 0.2769],
          [0.2777, 0.2780, 0.0000, 0.0000, 0.2777, 0.2773],
          [0.0000, 0.0000, 0.2780, 0.0000, 0.0000, 0.2777],
          [0.2769, 0.0000, 0.2779, 0.0000, 0.0000, 0.0000],
          [0.2765, 0.0000, 0.2778, 0.2782, 0.2784, 0.2785]],

         [[0.2778, 0.0000, 0.2778, 0.2778, 0.0000, 0.0000],
          [0.2778, 0.2778, 0.2778, 0.0000, 0.2778, 0.2778],
          [0.2778, 0.0000, 0.0000, 0.2778, 0.0000, 0.2778],
          [0.0000, 0.2778, 0.0000, 0.0000, 0.2778, 0.2778],
          [0.2778, 0.2778, 0.0000, 0